### PR TITLE
[UNET3D] Update RCPs due to !523 and !625

### PR DESCRIPTION
**Pull request by mmarcinkiewicz**
In https://github.com/mlcommons/training/pull/523 the distributed sampler was enabled, which required to use `drop_last_batch` setting, vs `pad_last_batch` as was being used previously. This changed the `samples_per_epoch` for each global batch size and required a different set of RPCs for GBS that do not divide the dataset evenly.

Furthermore, in https://github.com/mlcommons/training/pull/625, a bug in the implementation of the distributed samples was found, which might have affected convergence.

I regenerated all the RCPs (except for BS=2 which does not use the distributed sampler and divides the dataset evenly) to accommodate the changes. The change for GBS=32 and GBS=80 seems substantial, but please keep in mind that the number of samples to converge is more or less the same, so the total time to train should remain constant. Also, for GBS=64, the epochs to converge seems quite high, but after converting to samples to converge, it is reasonable.

GBS=32
old samples per epoch: 192
old RCP mean: 1974
new samples per epoch: 160
new RCP mean: 2409
ratio: 1.22, expected ratio (192/160): 1.2

GBS=56
old samples per epoch: 168
old RCP mean: 2213
new samples per epoch: 168
new RCP mean: 2300
ratio: 1.04, expected ratio: 1.00

GBS=64
old samples per epoch: 192
old RCP mean: ---
new samples per epoch: 128
new RCP mean: 3270.77
ratio: ---, expected ratio: 1.5, expected old RCP mean: 2180.51

GBS=80
old samples per epoch: 240
old RCP mean: 1618.75
new samples per epoch: 160
new RCP mean: 2462.51
ratio 1.52, expected ratio: 1.5

GBS=84
old RCP mean: 2233.25
new RCP mean: 2308.695652173913
ratio: 1.03, expected ratio: 1.0

The slight increase (3-4%) of the ratio might or might not be attributed to the fix to the distributed sampler.

### CODE REVIEW

**Comment by nv-rborkar** [comment]
@itayhubara please try this branch.

**Comment by xyhuang** [comment]
@mmarcinkiewicz could you please rebase the branch? thx

**Comment by nv-rborkar** [comment]
@itayhubara  did you get a chance to try these new RCPs?

**Comment by daisyden** [comment]
@mmarcinkiewicz, seems https://github.com/mlcommons/training/pull/625 is not merged, can we adopt it in the submission since it can avoid sample overlap among workers?

**Comment by itayhubara** [comment]
I gave it a try on my logs and it seems to work (my logs pass the RCP test as before) - you can merge it.

**Comment by mmarcinkiewicz** [comment]
@daisyden yes, the #625 should have been merged

**Comment by mmarcinkiewicz** [comment]
@xyhuang rebased

**Comment by nv-rborkar** [comment]
@drcanchi did you get a chance to try these RCPs?

**Comment by drcanchi** [comment]
@nv-rborkar : no objection to RCP change

**Pull request merged**
