### PR TITLE
Add training 3.0 ruleset

### PR DESCRIPTION
**Pull request by janekl**
Author: Jan Lasek, Nvidia (jlasek_at_nvidia_dot_com)

This pull request lays the groundwork for 3.0.0 library version for upcoming MLPerf submissions.

Expiring / new benchmarks will be removed / added in separate PRs.

### CODE REVIEW

**Comment by janekl** [comment]
Hello @xyhuang. I've created a separate MR as per your suggestion in https://github.com/mlcommons/logging/pull/295 - please review and stamp if everything looks good.

For the next steps for the recommender benchmark I suggest:
1. we prepare a PR that removes **dlrm** benchmark from **3.0.0**
2. we add **dlrmv2** (a.k.a. **dlrmv2_dcnv2**) in subsequent PRs - in fact this work has already been started, see:
- https://github.com/mlcommons/logging/pull/295
- https://github.com/mlcommons/logging/pull/297
- https://github.com/mlcommons/logging/pull/300.

Does it sound good? I can take care of this.

**Comment by erichan1** [comment]
@pgmpablo157321 or @xyhuang could you help review and test this? Also, is all this code replicated from benchmark to benchmark? I didn't realize this... it's kinda a lot.

**Comment by xyhuang** [comment]
thanks! @janekl @erichan1 we will review it. Right now we keep a complete copy of the rulesets and RCP numbers for each submission. We should probably think of changing that in the future if it isn't needed.

**Review by pgmpablo157321 — COMMENTED** [review]
@janekl please change this version
https://github.com/janekl/logging/blob/06b98cf82d05fd9220548c51779ebb6b77c3e38c/VERSION#L1
and resolve the conflicts.
Otherwise, LGTM

**Review by pgmpablo157321 — APPROVED** [review]

**Pull request merged**
