### PR TITLE
[DLRMv2] Compliance checker for new recommender benchmark model for MLPerf Training v3.0.0

### PR DESCRIPTION
**Pull request by janekl**
Author: Jan Lasek, Nvidia (jlasek_at_nvidia_dot_com)

This pull request add necessary changes to make compliance checker work for the new DLRMv2 benchmark. It also lays the groundwork for 3.0.0 library version.

### CODE REVIEW

**Comment by janekl** [comment]
Prerequisite: https://github.com/mlcommons/logging/pull/297

**Comment by xyhuang** [comment]
it might be better to add all the 3.0 rulesets in a stand alone commit, would you like to take a stab at that? a previous example can be found here #263 or let us know if you'd prefer others to do it and you can modify your patch to just add the new benchmark

**Comment by janekl** [comment]
> it might be better to add all the 3.0 rulesets in a stand alone commit, would you like to take a stab at that? a previous example can be found here #263 or let us know if you'd prefer others to do it and you can modify your patch to just add the new benchmark

Hi. I can add this in a separate PR (if anyone hasn't started working on that yet).

**Comment by janekl** [comment]
Hi @xyhuang and @pgmpablo157321. After merging https://github.com/mlcommons/logging/pull/301 I rebased the PR here and it is ready now. @erichan1 please stamp it if it looks good to you.

**Review by erichan1 — APPROVED** [review]

**Comment by erichan1** [comment]
@pgmpablo157321 please merge

**Pull request merged**
