### PR TITLE
Add GBS 6144 RCPs for GPT3 benchmark

### PR DESCRIPTION
**Pull request by ShriyaPalsamudram**
Add GBS 6144 RCP for GPT3 benchmark generated using megatron-lm

Pending: Google to update paxml generated RCP samples for the same GBS

### CODE REVIEW

**Comment by ZhiyuLi-goog** [comment]
Hi, @ShriyaPalsamudram,

I conducted 3 paxml runs of GBS 6144 RCP for the GPT-3 benchmark and obtained the 1409286144 num_epochs. Could you update the RCP file accordingly?

```
    "gpt3_ref_6144":
  {
    "Benchmark": "gpt3",
    "Creator": "Google & NVIDIA",
    "When": "Prior to 3.0 submission",
    "Platform": "TPU-v4-2048 / PaxML, 1024 H100-80GB / Megatron-LM",
    "BS": 6144,
    "Hyperparams": {
      "opt_base_learning_rate": 3e-5
    },
    "Epochs to converge": [
       1409286144, 1409286144, 1409286144, 1409286144, 1409286144, 1409286144
    ]
  },
```

**Comment by ShriyaPalsamudram** [comment]
@ZhiyuLi-goog thank you for collecting the data, I have updated the PR and marked it ready for review. 
Please approve so it can be merged.

**Review by ZhiyuLi-goog — APPROVED** [review]
Thank you Shriya. LGTM.

**Review by hiwotadese — APPROVED** [review]
lgtm

**Pull request merged**
