### PR TITLE
[Bert] update bs448 RCP

### PR DESCRIPTION
**Pull request by sgpyc**
DO NOT MERGE into the v2.0 folder.

BS448 RCP data based on Habana's HP set from the training v2.0 round.
Intend to check in to the v2.1 folder.

### CODE REVIEW

**Comment by johntran-nv** [comment]
Hi @sgpyc , can you confirm the exact reference code you used to generate these so others can reproduce?  

Also, does this repro on TPUv3?  That would be best for others to reproduce.

**Comment by johntran-nv** [comment]
Hi @sgpyc , are the changes in https://github.com/mlcommons/training/pull/507 included in your latest runs? We believe input pipeline changes could be the difference, and that PR mentions some changes to the input pipeline.

**Comment by pgmpablo157321** [comment]
@sgpyc v2.1 folder has been created and is currently in the master branch

**Comment by sgpyc** [comment]
Moved to the v2.1 folder. Please consider merging.

I did tried the HP set on TPUv3-32 with TF2.10 for 2 runs. They converged with 5768 & 5600 steps. BERT at low batch sizes seem to have a larger variance in convergence, but it's quite clear this HP set does converge.

**Review by johntran-nv — APPROVED** [review]

**Review by erichan1 — APPROVED** [review]

**Review by pgmpablo157321 — APPROVED** [review]

**Pull request merged**
