### PR TITLE
[Compliance] Skipping weight init. check for minigo in v2.0 training submission

### PR DESCRIPTION
**Pull request by shangw-nvidia**
This is a proposal to skip weight init. check just for minigo v2.0 submission. @emizan76 FYI, @johntran-nv already discussed with @petermattson about this requirement change, but this will probably be brought up in the training WG meeting as well.

### CODE REVIEW

**Review by emizan76 — COMMENTED** [review]
Since I have been through a lot of frustration and pain enabling, disabling, changing to warning, and re-enabling weight initialization, and running tests with it, may I know what the reason is for selectively disablng it for this particular benchmark? Why does it matter for the rest of the benchmarks and it does matter for minigo?

**Comment by yuanzhedong** [comment]
Hi @johntran-nv @emizan76 @shangw-nvidia, any update here?

**Comment by johntran-nv** [comment]
The Training WG agreed on 4/28 that this is ok, so I think it's ok the merge.

**Comment by shangw-nvidia** [comment]
@emizan76 @xyhuang could either of you approve this PR? Thanks!

**Review by emizan76 — APPROVED** [review]

**Pull request merged**
