### PR TITLE
[DLRMv2] Add constants for the new MLPerf Training recommendation benchmark

### PR DESCRIPTION
**Pull request by janekl**
Author: Jan Lasek, Nvidia (jlasek_at_nvidia_dot_com)

### CODE REVIEW

**Review by erichan1 — APPROVED** [review]

**Comment by erichan1** [comment]
@pgmpablo157321 Can you approve this? I also can't approve.

**Review by pgmpablo157321 — APPROVED** [review]
LGTM

**Comment by erichan1** [comment]
> LGTM
@pgmpablo157321 
Can you also merge? Don't see the merge button. And Jan probably can't either.

**Comment by pgmpablo157321** [comment]
Merged

**Pull request merged**
