### PR TITLE
[SSD] RCPs updates for v3.0

### PR DESCRIPTION
**Pull request by ahmadki**

### CODE REVIEW

**Comment by xyhuang** [comment]
@erichan1 is training WG good with merging this? thx

**Comment by nv-rborkar** [comment]
@drcanchi can you please review and approve.

**Comment by drcanchi** [comment]
@nv-rborkar : Looks good to me.

**Review by nv-rborkar — APPROVED** [review]

**Comment by nv-rborkar** [comment]
Reviewed by WG. Merging.

**Pull request merged**
