### PR TITLE
Updated parser script and readme

### PR DESCRIPTION
**Pull request by nv-eric-hw**
parse_mlperf.py - v5.2
README.md - Reflects v5

### CODE REVIEW

**Comment by nv-eric-hw** [comment]
@googlebot I signed it!

**Comment by psyhtest** [comment]
recheck

**Comment by xyhuang** [comment]
@nv-eric-hw would you mind if we move `/log_parsers` to `/power/log_parsers`?
Merging for now and we can have the move in a follow-up patch.

**Comment by nv-eric-hw** [comment]
Hi @xyhuang, sure, I'm open to any optimizations.

Thanks.

**Pull request merged**
