### PR TITLE
Normalize Energy when perf. is normalized to RCP-mean

### PR DESCRIPTION
**Pull request by nv-rborkar**
In MLPerf Training, performance is sometimes normalized based on a scaling factor in scenarios such as:

- Test passes RCP check but is faster than RCP-mean (automatically done by repo checker)
-  Reviewers WG decides to normalize a score to RCP-mean for any reasons such as RCP failures

Energy (perf *power) should also be normalized in such cases.

### CODE REVIEW

**Comment by nv-rborkar** [comment]
@sgpyc can you review this PR and provide feedback in comments?

**Review by sgpyc — APPROVED** [review]
The change is reasonable to me.

Because this is a last minute change, I suggest leaving some flexibility to the review committee in case they have concerns.

**Comment by erichan1** [comment]
Just to clarify, we're scaling the power score based on scaling factor of number of steps to train? Not saying that there shouldn't be a scaling factor, but it's not obvious to me that this is the right way to do it.

**Comment by nv-rborkar** [comment]
We are scaling energy score (time*power) when time gets scaled by a scaling factor. 
RCP normalization is like penalizing a score which was fast, Energy should get penalized similarly as well.

This scenario was not discussed by power taskforce. PR has the most logical solution but we can discuss more during review & have power taskforce weigh in as well.

**Review by hiwotadese — APPROVED** [review]

**Comment by nv-rborkar** [comment]
@pgmpablo157321 can you please review this once to confirm it doesn't break any of your recent changes to include power & perf in result summary.

**Review by pgmpablo157321 — APPROVED** [review]
LGTM

**Pull request merged**
