### PR TITLE
[RNN-T] RCPs update - disabled bucketing

### PR DESCRIPTION
**Pull request by mwawrzos**
refers to https://github.com/mlcommons/training_policies/pull/453

1k and 3k update TBD

### CODE REVIEW

**Comment by qpjaada** [comment]
@mwawrzos - not sure what the policy is - but shouldn't the 1.0.0 RCPs stay unchanged? 
I think this should be updated only for the 1.1.0 RCPs.....

**Comment by mwawrzos** [comment]
Sure.. my bad.. thanks, fixed

**Comment by qpjaada** [comment]
what's the plan for updating the RCPs for BS=1024, 3072? I presume we need to generate RCPs for that with `data_train_num_buckets=1`. At a minimum, it would be useful to create an issue that keeps track of this.

**Comment by mwawrzos** [comment]
I can update the numbers in August, as I'm on vacation now. I opened an issue here: https://github.com/mlcommons/logging/issues/147

**Review by qpjaada — APPROVED** [review]
looks good

**Review by emizan76 — APPROVED** [review]

**Review by xyhuang — APPROVED** [review]

**Pull request merged**
