### PR TITLE
Add support for compliance for 4.1

### PR DESCRIPTION
**Pull request by mmarcinkiewicz**
Some changes slipped and were not changed in https://github.com/mlcommons/logging/pull/381
This PR fixes it. Apologies for the hassle

### CODE REVIEW

**Comment by mmarcinkiewicz** [comment]
@xyhuang could you please take a look?

**Comment by mmarcinkiewicz** [comment]
Though when I use my branch, I'm getting

python3 -m mlperf_logging.compliance_checker --usage training --ruleset 4.1.0 --log_output <> <>
INFO - Running compliance on file: <>
INFO -  Compliance checks: training_4.1.0/common.yaml
INFO -  Compliance checks: training_4.0.0/closed_common.yaml
INFO -  Compliance checks: training_4.0.0/closed_llama2_70b_lora.yaml

I am unable to find why it would be doing that

**Comment by mmarcinkiewicz** [comment]
It's working now

**Comment by xyhuang** [comment]
hi @mmarcinkiewicz thanks a lot for addressing this!

**Review by xyhuang — APPROVED** [review]

**Pull request merged**
